## CATEGORIES
GET http://localhost:3000/categories
###
GET http://localhost:3000/categories/1
###
POST http://localhost:3000/categories
Content-Type: application/json

    {
        "name": "Category 4"
    }

###
PATCH http://localhost:3000/categories/1
Content-Type: application/json

    {
        "name": "Category 1 Updated"
    }
###
DELETE http://localhost:3000/categories/2


===========================================
## PRODUCTS

###
GET http://localhost:3000/products
###
GET http://localhost:3000/products/0
###
POST http://localhost:3000/products
Content-Type: application/json

    {
        "name": "Product 1",
        "price": 200,
        "categoryId": 0
    }
###
PATCH http://localhost:3000/products/1
Content-Type: application/json

    {
        "name": "Product 1 Updated",
        "price": 200
    }
###
DELETE http://localhost:3000/products/3